CREATE TABLE IF NOT EXISTS roles (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    uuid VARCHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role INT NOT NULL DEFAULT 2
    FOREIGN KEY (role)
        REFERENCES roles(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS priority (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    priority VARCHAR(255) NOT NULL
);